# Generated by Django 3.2.4 on 2021-06-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_first_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_status',
            field=models.CharField(blank=True, default='Otvorena', max_length=30, null=True),
        ),
    ]
