# Generated by Django 3.2.4 on 2021-06-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_game_game_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_status',
            field=models.CharField(blank=True, default='otvorena', max_length=30),
        ),
    ]
