# Generated by Django 3.2.4 on 2021-06-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_game_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='board_column',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='move',
            name='board_row',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
